// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvosmrargaueilecbycn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2b3NtcmFyZ2F1ZWlsZWNieWNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNDc4MDUsImV4cCI6MjA2MDkyMzgwNX0.W05d74uqohoTa5-4Vdgh9GTi3Zpa1SlFtDf6GwaMlww";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);